const json_data = {
  books: [
    {
      cover: "https://pictures.abebooks.com/isbn/9780553136951-us.jpg",
      title: "Something Wicked This Way Comes",
      isbn13: "978-0-380-72940-1",
      is_awesome: true,
      id: 2,
      year_published: 1997,
      author: "Ray Bradbury",
      num_pages: 293,
      isbn10: "0-380-72940-7",
      have_read: false,
    },
    {
      cover: "https://m.media-amazon.com/images/I/81dy4cfPGuL._SY522_.jpg",
      title: "One Hundred Years of Solitude",
      isbn13: null,
      is_awesome: false,
      id: 3,
      year_published: 1970,
      author: "Gabriel Garcia Marquez",
      num_pages: 383,
      isbn10: "0-380-01503-X",
      have_read: true,
    },
    {
      cover:
        "https://i5.walmartimages.com/seo/Snow-Crash-Hardcover-9780613361620_f11eea3c-5e60-4a1b-936b-67c9c4455e27_1.0a9c061d4600a35fb739ad85e9e9aa06.jpeg",
      title: "Snow Crash",
      isbn13: "978-061336162",
      is_awesome: true,
      id: 4,
      year_published: 1992,
      author: "Neal Stephenson",
      num_pages: 470,
      isbn10: null,
      have_read: false,
    },
    {
      cover:
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1404613595i/13.jpg",
      title: "The Ultimate Hitchiker's Guide To The Galaxy",
      isbn13: "978-0-645-45374-7",
      is_awesome: true,
      id: 5,
      year_published: 2002,
      author: "Douglas Adams",
      num_pages: 815,
      isbn10: null,
      have_read: false,
    },
    {
      cover:
        "https://garthnix.com/wp-content/uploads/2022/01/cover-old-kingdom-3-boxed-set-pichi.jpg",
      title: "Sabriel",
      isbn13: null,
      is_awesome: true,
      id: 8,
      year_published: 1995,
      author: "Garth Nix",
      num_pages: 509,
      isbn10: "0-06-447183-7",
      have_read: true,
    },
    {
      cover:
        "https://s3-ap-southeast-2.amazonaws.com/cloud1.berkelouw.com.au/new_books/9781912559329.jpg",
      title: "On Cats — An Anthology",
      isbn13: "978-1-912559-32-9",
      is_awesome: true,
      id: 13,
      year_published: 2021,
      author: "Various",
      num_pages: 148,
      isbn10: "",
      have_read: true,
    },
    {
      cover:
        "https://m.media-amazon.com/images/I/519JNfG+uNL._AC_UF1000,1000_QL80_.jpg",
      title: "Consider Phlebas",
      isbn13: "978-0-356-52163-3",
      is_awesome: true,
      id: 16,
      year_published: 1987,
      author: "Iain M. Banks",
      num_pages: 515,
      isbn10: "",
      have_read: true,
    },
    {
      cover:
        "https://www.carnegielibrary.org/wp-content/uploads/2018/03/Crypto.jpg",
      title: "Cryptonomicon",
      isbn13: "978-0-380-78862-0",
      is_awesome: true,
      id: 17,
      year_published: 2000,
      author: "Neal Stephenson",
      num_pages: 918,
      isbn10: "0-380-78862-4",
      have_read: true,
    },
    {
      cover:
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1223645907i/102266.jpg",
      title: "Ill Met In Lankhmar",
      isbn13: "9781565048942",
      is_awesome: true,
      id: 18,
      year_published: 1995,
      author: "Fritz Lieber",
      num_pages: 494,
      isbn10: null,
      have_read: true,
    },
    {
      cover: "https://atomicbooks.com/cdn/shop/products/kingcity_1600x.jpg",
      title: "King City",
      isbn13: "978-1-60706-510-4",
      is_awesome: true,
      id: 19,
      year_published: 2017,
      author: "Brandon Graham",
      num_pages: 424,
      isbn10: null,
      have_read: true,
    },
    {
      cover:
        "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1383249816i/939740.jpg",
      title: "The Integral Trees",
      isbn13: null,
      is_awesome: true,
      id: 21,
      year_published: null,
      author: "Larry Niven",
      num_pages: null,
      isbn10: null,
      have_read: false,
    },
    {
      cover:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxejkzsZRVBltykeshvpMKFaxsNM_0iTQSIQ&s",
      title: "The War Between The Pitiful Teachers And The Splendid Kids",
      isbn13: null,
      is_awesome: true,
      id: 22,
      year_published: null,
      author: "Stanley Kiesel",
      num_pages: null,
      isbn10: null,
      have_read: false,
    },
    {
      cover: null,
      title: "The Everything Box",
      isbn13: null,
      is_awesome: true,
      id: 28,
      year_published: 2016,
      author: "Richard Kadrey",
      num_pages: 369,
      isbn10: null,
      have_read: true,
    },
  ],
  count: 13,
};

export default json_data;
